version: '3.9'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DJANGO_SETTINGS_MODULE=ecommerce.settings
    volumes:
      - .:/app   # Mount local code for hot reload
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
      - elasticsearch

  celery:
    build: .
    entrypoint: [""]   # override Dockerfile entrypoint
    command: celery -A ecommerce worker --loglevel=info
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - redis

  celery-beat:
    build: .
    entrypoint: [""]   # override Dockerfile entrypoint
    command: celery -A ecommerce beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  esdata:
