# Generated by Django 5.1.6 on 2025-08-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners')),
                ('deal_type', models.CharField(choices=[('Daily Deal', 'Daily Deal'), ('Discount', 'Discount'), ('Limited Time', 'Limited Time'), ('Featured', 'Featured'), ('Custom', 'Custom')], default='custom', max_length=20)),
                ('link', models.CharField(max_length=200)),
                ('title', models.CharField(default='Food', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=3, unique=True)),
                ('rate', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main headline (e.g. Earphones)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Short description of the banner')),
                ('deal_type', models.CharField(choices=[('Daily Deal', 'Daily Deal'), ('Discount', 'Discount'), ('Limited Time', 'Limited Time'), ('Featured', 'Featured'), ('Custom', 'Custom')], default='custom', max_length=20)),
                ('price_prefix', models.CharField(blank=True, help_text="Text like 'Today:'", max_length=50)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Price (e.g. 247.99)', max_digits=10, null=True)),
                ('image_desktop', models.ImageField(blank=True, null=True, upload_to='sliders/desktop/')),
                ('image_mobile', models.ImageField(blank=True, null=True, upload_to='sliders/mobile/')),
                ('link_url', models.URLField(blank=True, help_text='Optional full link to a product, category, or page')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Slider order/priority')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
