# Generated by Django 5.1.6 on 2025-08-30 20:27

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='delivery_returns',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='We offer free standard shipping on all orders', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='I sell good products only', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='features',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='Black', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='Black', null=True),
        ),
    ]
