# Generated by Django 5.1.6 on 2025-08-28 10:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('subject_template', models.CharField(max_length=200)),
                ('html_template', models.TextField()),
                ('text_template', models.TextField(blank=True, help_text='Optional plain-text fallback')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="(e.g., 'buyers', 'vendors', 'ghana').", max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
                ('from_email', models.EmailField(max_length=254)),
                ('preheader', models.CharField(blank=True, max_length=180)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('cancelled', 'Cancelled')], default='draft', max_length=12)),
                ('batch_size', models.PositiveIntegerField(default=500)),
                ('throttle_per_min', models.PositiveIntegerField(default=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='newsletter.newslettertemplate')),
                ('exclude_tags', models.ManyToManyField(blank=True, related_name='exclude_from_campaigns', to='newsletter.tag')),
                ('include_tags', models.ManyToManyField(blank=True, related_name='include_in_campaigns', to='newsletter.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('first_name', models.CharField(blank=True, max_length=80)),
                ('last_name', models.CharField(blank=True, max_length=80)),
                ('locale', models.CharField(blank=True, max_length=12)),
                ('country', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('bounce_count', models.PositiveIntegerField(default=0)),
                ('confirm_token', models.CharField(blank=True, default='', max_length=64)),
                ('unsubscribe_token', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(blank=True, to='newsletter.tag')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered', models.BooleanField(default=False)),
                ('opened', models.BooleanField(default=False)),
                ('bounced', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='newsletter.campaign')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter.subscriber')),
            ],
            options={
                'unique_together': {('campaign', 'subscriber')},
            },
        ),
    ]
